server:
  port: 8060

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
      auto: false
    sqs:
      url: https://sqs.ap-south-1.amazonaws.com/750120836441/Test_Queue
      pollingThreads: 1
      pollingRate: 1000

    credentials:
      key:
      secret: 
