server:
  port: 8080

cloud:
  aws:
    stack:
      auto: false

    region:
      static: ap-south-1
      auto: false

    sqs:
      url: https://sqs.ap-south-1.amazonaws.com/***/***
      pollingThreads: 1
      pollingRate: 10000

    credentials:
      key:
      secret:
